version: '3.8'

services:
  postgres:
    image: 'postgres:14.4-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data:cached'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres:
